### PR TITLE
move the responsive check above the setting of the width based on the cols

### PR DESCRIPTION
**Pull request by dsmorse**
This move fixes a bug where the layout could shrink after a drag finished, on browsers that don't fully support the min-width settings.

### CODE REVIEW

**Comment by fhawkes** [comment]
Thanks for the PR. I actually caught this issue the other day. I had been working on a patch that has a fix for it but haven't pushed it up yet. Should be up soon.

**Comment by dsmorse** [comment]
Great.  look forward to seeing it.

**Comment by dsmorse** [comment]
I pulled the 0.6.5 and started playing with the new center_widget code... if wasn't happy with a # cols of 'auto', so I updated the pull request.

**Comment by fhawkes** [comment]
center_widgets is not intended to be used when in responsive mode. How could you center widgets that are already stretched the full width of the container? I'm sorry for the lack of documentation for this I guess Ideally we should just check to see if is_responsive() is false before we try centering widgets.

**Comment by dsmorse** [comment]
Maybe my responsive mode config is not the same as yours.  I have multiple columns and the columns stretch to the full width, but there are still multiple columns and a widget may be less than the full width, therefore the center widgets would move them all to the center column of the responsive layout.  Honestly I'm not using the center_widgets, but I saw it was added and tried it, and it blew up... however the shit_cols which it calls has been very useful to me

**Pull request closed without merging**
